name: generate svg with grades

on:
  schedule:
    - cron: "*/10 * * * *" 
  
  workflow_dispatch:
  
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: generate svg with grades
        uses: andrebrito16/iac-svg-generator/svg-only@main
        env:
          IAC_TOKEN: ${{ secrets.IAC_TOKEN }}
      - name: push grades to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          keep_history: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}